title: "H4x Blog"
description: "A hacker-style dark theme blog powered by GitHub Pages + Jekyll"
url: "" # e.g. https://<username>.github.io
baseurl: "" # e.g. /myblog

theme: null
plugins:
  - jekyll-feed

# Author info
author:
  name: "Robin"
  email: "you@example.com"

lang: bn-BD

# Build
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Feed config
feed:
  path: feed.xml

# Exclude
exclude:
  - README.md
